logging:
  level:
    '[org.springframework.web]': debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cmblxxo7uwm2.ap-northeast-2.rds.amazonaws.com:3306/toonder?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: toonder19212121
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: trues
